// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/requestrewriterule"
	"github.com/looplj/axonhub/internal/objects"
)

// RequestRewriteRule is the model entity for the RequestRewriteRule schema.
type RequestRewriteRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int `json:"deleted_at,omitempty"`
	// Owner of this rule
	UserID int `json:"user_id,omitempty"`
	// Rule name, unique per user
	Name string `json:"name,omitempty"`
	// Rule description
	Description string `json:"description,omitempty"`
	// Exact model name or regex pattern (applied to the client's original model name)
	ModelPattern string `json:"model_pattern,omitempty"`
	// Status holds the value of the "status" field.
	Status requestrewriterule.Status `json:"status,omitempty"`
	// Field value maps: first matching source value wins; empty replacement clears the field
	FieldMaps    []objects.RequestRewriteFieldMap `json:"field_maps,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RequestRewriteRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case requestrewriterule.FieldFieldMaps:
			values[i] = new([]byte)
		case requestrewriterule.FieldID, requestrewriterule.FieldDeletedAt, requestrewriterule.FieldUserID:
			values[i] = new(sql.NullInt64)
		case requestrewriterule.FieldName, requestrewriterule.FieldDescription, requestrewriterule.FieldModelPattern, requestrewriterule.FieldStatus:
			values[i] = new(sql.NullString)
		case requestrewriterule.FieldCreatedAt, requestrewriterule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RequestRewriteRule fields.
func (_m *RequestRewriteRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case requestrewriterule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case requestrewriterule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case requestrewriterule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case requestrewriterule.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = int(value.Int64)
			}
		case requestrewriterule.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case requestrewriterule.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case requestrewriterule.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case requestrewriterule.FieldModelPattern:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_pattern", values[i])
			} else if value.Valid {
				_m.ModelPattern = value.String
			}
		case requestrewriterule.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = requestrewriterule.Status(value.String)
			}
		case requestrewriterule.FieldFieldMaps:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field field_maps", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.FieldMaps); err != nil {
					return fmt.Errorf("unmarshal field field_maps: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RequestRewriteRule.
// This includes values selected through modifiers, order, etc.
func (_m *RequestRewriteRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RequestRewriteRule.
// Note that you need to call RequestRewriteRule.Unwrap() before calling this method if this RequestRewriteRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RequestRewriteRule) Update() *RequestRewriteRuleUpdateOne {
	return NewRequestRewriteRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RequestRewriteRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RequestRewriteRule) Unwrap() *RequestRewriteRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RequestRewriteRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RequestRewriteRule) String() string {
	var builder strings.Builder
	builder.WriteString("RequestRewriteRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("model_pattern=")
	builder.WriteString(_m.ModelPattern)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("field_maps=")
	builder.WriteString(fmt.Sprintf("%v", _m.FieldMaps))
	builder.WriteByte(')')
	return builder.String()
}

// RequestRewriteRules is a parsable slice of RequestRewriteRule.
type RequestRewriteRules []*RequestRewriteRule
