// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/requestrewriterule"
	"github.com/looplj/axonhub/internal/objects"
)

// RequestRewriteRuleCreate is the builder for creating a RequestRewriteRule entity.
type RequestRewriteRuleCreate struct {
	config
	mutation *RequestRewriteRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *RequestRewriteRuleCreate) SetCreatedAt(v time.Time) *RequestRewriteRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RequestRewriteRuleCreate) SetNillableCreatedAt(v *time.Time) *RequestRewriteRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RequestRewriteRuleCreate) SetUpdatedAt(v time.Time) *RequestRewriteRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RequestRewriteRuleCreate) SetNillableUpdatedAt(v *time.Time) *RequestRewriteRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *RequestRewriteRuleCreate) SetDeletedAt(v int) *RequestRewriteRuleCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *RequestRewriteRuleCreate) SetNillableDeletedAt(v *int) *RequestRewriteRuleCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *RequestRewriteRuleCreate) SetUserID(v int) *RequestRewriteRuleCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *RequestRewriteRuleCreate) SetNillableUserID(v *int) *RequestRewriteRuleCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *RequestRewriteRuleCreate) SetName(v string) *RequestRewriteRuleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *RequestRewriteRuleCreate) SetDescription(v string) *RequestRewriteRuleCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *RequestRewriteRuleCreate) SetNillableDescription(v *string) *RequestRewriteRuleCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetModelPattern sets the "model_pattern" field.
func (_c *RequestRewriteRuleCreate) SetModelPattern(v string) *RequestRewriteRuleCreate {
	_c.mutation.SetModelPattern(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *RequestRewriteRuleCreate) SetStatus(v requestrewriterule.Status) *RequestRewriteRuleCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RequestRewriteRuleCreate) SetNillableStatus(v *requestrewriterule.Status) *RequestRewriteRuleCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetFieldMaps sets the "field_maps" field.
func (_c *RequestRewriteRuleCreate) SetFieldMaps(v []objects.RequestRewriteFieldMap) *RequestRewriteRuleCreate {
	_c.mutation.SetFieldMaps(v)
	return _c
}

// Mutation returns the RequestRewriteRuleMutation object of the builder.
func (_c *RequestRewriteRuleCreate) Mutation() *RequestRewriteRuleMutation {
	return _c.mutation
}

// Save creates the RequestRewriteRule in the database.
func (_c *RequestRewriteRuleCreate) Save(ctx context.Context) (*RequestRewriteRule, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequestRewriteRuleCreate) SaveX(ctx context.Context) *RequestRewriteRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestRewriteRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestRewriteRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RequestRewriteRuleCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if requestrewriterule.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized requestrewriterule.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := requestrewriterule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if requestrewriterule.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized requestrewriterule.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := requestrewriterule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := requestrewriterule.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := requestrewriterule.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := requestrewriterule.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.FieldMaps(); !ok {
		v := requestrewriterule.DefaultFieldMaps
		_c.mutation.SetFieldMaps(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequestRewriteRuleCreate) check() error {
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "RequestRewriteRule.deleted_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RequestRewriteRule.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := requestrewriterule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RequestRewriteRule.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "RequestRewriteRule.description"`)}
	}
	if _, ok := _c.mutation.ModelPattern(); !ok {
		return &ValidationError{Name: "model_pattern", err: errors.New(`ent: missing required field "RequestRewriteRule.model_pattern"`)}
	}
	if v, ok := _c.mutation.ModelPattern(); ok {
		if err := requestrewriterule.ModelPatternValidator(v); err != nil {
			return &ValidationError{Name: "model_pattern", err: fmt.Errorf(`ent: validator failed for field "RequestRewriteRule.model_pattern": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RequestRewriteRule.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := requestrewriterule.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RequestRewriteRule.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FieldMaps(); !ok {
		return &ValidationError{Name: "field_maps", err: errors.New(`ent: missing required field "RequestRewriteRule.field_maps"`)}
	}
	return nil
}

func (_c *RequestRewriteRuleCreate) sqlSave(ctx context.Context) (*RequestRewriteRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequestRewriteRuleCreate) createSpec() (*RequestRewriteRule, *sqlgraph.CreateSpec) {
	var (
		_node = &RequestRewriteRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requestrewriterule.Table, sqlgraph.NewFieldSpec(requestrewriterule.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(requestrewriterule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(requestrewriterule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(requestrewriterule.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(requestrewriterule.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(requestrewriterule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(requestrewriterule.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.ModelPattern(); ok {
		_spec.SetField(requestrewriterule.FieldModelPattern, field.TypeString, value)
		_node.ModelPattern = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(requestrewriterule.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.FieldMaps(); ok {
		_spec.SetField(requestrewriterule.FieldFieldMaps, field.TypeJSON, value)
		_node.FieldMaps = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RequestRewriteRule.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestRewriteRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RequestRewriteRuleCreate) OnConflict(opts ...sql.ConflictOption) *RequestRewriteRuleUpsertOne {
	_c.conflict = opts
	return &RequestRewriteRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RequestRewriteRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RequestRewriteRuleCreate) OnConflictColumns(columns ...string) *RequestRewriteRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RequestRewriteRuleUpsertOne{
		create: _c,
	}
}

type (
	// RequestRewriteRuleUpsertOne is the builder for "upsert"-ing
	//  one RequestRewriteRule node.
	RequestRewriteRuleUpsertOne struct {
		create *RequestRewriteRuleCreate
	}

	// RequestRewriteRuleUpsert is the "OnConflict" setter.
	RequestRewriteRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *RequestRewriteRuleUpsert) SetUpdatedAt(v time.Time) *RequestRewriteRuleUpsert {
	u.Set(requestrewriterule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsert) UpdateUpdatedAt() *RequestRewriteRuleUpsert {
	u.SetExcluded(requestrewriterule.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RequestRewriteRuleUpsert) SetDeletedAt(v int) *RequestRewriteRuleUpsert {
	u.Set(requestrewriterule.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsert) UpdateDeletedAt() *RequestRewriteRuleUpsert {
	u.SetExcluded(requestrewriterule.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *RequestRewriteRuleUpsert) AddDeletedAt(v int) *RequestRewriteRuleUpsert {
	u.Add(requestrewriterule.FieldDeletedAt, v)
	return u
}

// SetName sets the "name" field.
func (u *RequestRewriteRuleUpsert) SetName(v string) *RequestRewriteRuleUpsert {
	u.Set(requestrewriterule.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsert) UpdateName() *RequestRewriteRuleUpsert {
	u.SetExcluded(requestrewriterule.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *RequestRewriteRuleUpsert) SetDescription(v string) *RequestRewriteRuleUpsert {
	u.Set(requestrewriterule.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsert) UpdateDescription() *RequestRewriteRuleUpsert {
	u.SetExcluded(requestrewriterule.FieldDescription)
	return u
}

// SetModelPattern sets the "model_pattern" field.
func (u *RequestRewriteRuleUpsert) SetModelPattern(v string) *RequestRewriteRuleUpsert {
	u.Set(requestrewriterule.FieldModelPattern, v)
	return u
}

// UpdateModelPattern sets the "model_pattern" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsert) UpdateModelPattern() *RequestRewriteRuleUpsert {
	u.SetExcluded(requestrewriterule.FieldModelPattern)
	return u
}

// SetStatus sets the "status" field.
func (u *RequestRewriteRuleUpsert) SetStatus(v requestrewriterule.Status) *RequestRewriteRuleUpsert {
	u.Set(requestrewriterule.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsert) UpdateStatus() *RequestRewriteRuleUpsert {
	u.SetExcluded(requestrewriterule.FieldStatus)
	return u
}

// SetFieldMaps sets the "field_maps" field.
func (u *RequestRewriteRuleUpsert) SetFieldMaps(v []objects.RequestRewriteFieldMap) *RequestRewriteRuleUpsert {
	u.Set(requestrewriterule.FieldFieldMaps, v)
	return u
}

// UpdateFieldMaps sets the "field_maps" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsert) UpdateFieldMaps() *RequestRewriteRuleUpsert {
	u.SetExcluded(requestrewriterule.FieldFieldMaps)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RequestRewriteRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RequestRewriteRuleUpsertOne) UpdateNewValues() *RequestRewriteRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(requestrewriterule.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(requestrewriterule.FieldUserID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RequestRewriteRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RequestRewriteRuleUpsertOne) Ignore() *RequestRewriteRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestRewriteRuleUpsertOne) DoNothing() *RequestRewriteRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestRewriteRuleCreate.OnConflict
// documentation for more info.
func (u *RequestRewriteRuleUpsertOne) Update(set func(*RequestRewriteRuleUpsert)) *RequestRewriteRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestRewriteRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RequestRewriteRuleUpsertOne) SetUpdatedAt(v time.Time) *RequestRewriteRuleUpsertOne {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsertOne) UpdateUpdatedAt() *RequestRewriteRuleUpsertOne {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RequestRewriteRuleUpsertOne) SetDeletedAt(v int) *RequestRewriteRuleUpsertOne {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *RequestRewriteRuleUpsertOne) AddDeletedAt(v int) *RequestRewriteRuleUpsertOne {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsertOne) UpdateDeletedAt() *RequestRewriteRuleUpsertOne {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *RequestRewriteRuleUpsertOne) SetName(v string) *RequestRewriteRuleUpsertOne {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsertOne) UpdateName() *RequestRewriteRuleUpsertOne {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *RequestRewriteRuleUpsertOne) SetDescription(v string) *RequestRewriteRuleUpsertOne {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsertOne) UpdateDescription() *RequestRewriteRuleUpsertOne {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.UpdateDescription()
	})
}

// SetModelPattern sets the "model_pattern" field.
func (u *RequestRewriteRuleUpsertOne) SetModelPattern(v string) *RequestRewriteRuleUpsertOne {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.SetModelPattern(v)
	})
}

// UpdateModelPattern sets the "model_pattern" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsertOne) UpdateModelPattern() *RequestRewriteRuleUpsertOne {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.UpdateModelPattern()
	})
}

// SetStatus sets the "status" field.
func (u *RequestRewriteRuleUpsertOne) SetStatus(v requestrewriterule.Status) *RequestRewriteRuleUpsertOne {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsertOne) UpdateStatus() *RequestRewriteRuleUpsertOne {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.UpdateStatus()
	})
}

// SetFieldMaps sets the "field_maps" field.
func (u *RequestRewriteRuleUpsertOne) SetFieldMaps(v []objects.RequestRewriteFieldMap) *RequestRewriteRuleUpsertOne {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.SetFieldMaps(v)
	})
}

// UpdateFieldMaps sets the "field_maps" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsertOne) UpdateFieldMaps() *RequestRewriteRuleUpsertOne {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.UpdateFieldMaps()
	})
}

// Exec executes the query.
func (u *RequestRewriteRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestRewriteRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestRewriteRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RequestRewriteRuleUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RequestRewriteRuleUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RequestRewriteRuleCreateBulk is the builder for creating many RequestRewriteRule entities in bulk.
type RequestRewriteRuleCreateBulk struct {
	config
	err      error
	builders []*RequestRewriteRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the RequestRewriteRule entities in the database.
func (_c *RequestRewriteRuleCreateBulk) Save(ctx context.Context) ([]*RequestRewriteRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RequestRewriteRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestRewriteRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequestRewriteRuleCreateBulk) SaveX(ctx context.Context) []*RequestRewriteRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestRewriteRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestRewriteRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RequestRewriteRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestRewriteRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RequestRewriteRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *RequestRewriteRuleUpsertBulk {
	_c.conflict = opts
	return &RequestRewriteRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RequestRewriteRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RequestRewriteRuleCreateBulk) OnConflictColumns(columns ...string) *RequestRewriteRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RequestRewriteRuleUpsertBulk{
		create: _c,
	}
}

// RequestRewriteRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of RequestRewriteRule nodes.
type RequestRewriteRuleUpsertBulk struct {
	create *RequestRewriteRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RequestRewriteRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RequestRewriteRuleUpsertBulk) UpdateNewValues() *RequestRewriteRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(requestrewriterule.FieldCreatedAt)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(requestrewriterule.FieldUserID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RequestRewriteRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RequestRewriteRuleUpsertBulk) Ignore() *RequestRewriteRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestRewriteRuleUpsertBulk) DoNothing() *RequestRewriteRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestRewriteRuleCreateBulk.OnConflict
// documentation for more info.
func (u *RequestRewriteRuleUpsertBulk) Update(set func(*RequestRewriteRuleUpsert)) *RequestRewriteRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestRewriteRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RequestRewriteRuleUpsertBulk) SetUpdatedAt(v time.Time) *RequestRewriteRuleUpsertBulk {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsertBulk) UpdateUpdatedAt() *RequestRewriteRuleUpsertBulk {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RequestRewriteRuleUpsertBulk) SetDeletedAt(v int) *RequestRewriteRuleUpsertBulk {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *RequestRewriteRuleUpsertBulk) AddDeletedAt(v int) *RequestRewriteRuleUpsertBulk {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsertBulk) UpdateDeletedAt() *RequestRewriteRuleUpsertBulk {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *RequestRewriteRuleUpsertBulk) SetName(v string) *RequestRewriteRuleUpsertBulk {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsertBulk) UpdateName() *RequestRewriteRuleUpsertBulk {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *RequestRewriteRuleUpsertBulk) SetDescription(v string) *RequestRewriteRuleUpsertBulk {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsertBulk) UpdateDescription() *RequestRewriteRuleUpsertBulk {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.UpdateDescription()
	})
}

// SetModelPattern sets the "model_pattern" field.
func (u *RequestRewriteRuleUpsertBulk) SetModelPattern(v string) *RequestRewriteRuleUpsertBulk {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.SetModelPattern(v)
	})
}

// UpdateModelPattern sets the "model_pattern" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsertBulk) UpdateModelPattern() *RequestRewriteRuleUpsertBulk {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.UpdateModelPattern()
	})
}

// SetStatus sets the "status" field.
func (u *RequestRewriteRuleUpsertBulk) SetStatus(v requestrewriterule.Status) *RequestRewriteRuleUpsertBulk {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsertBulk) UpdateStatus() *RequestRewriteRuleUpsertBulk {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.UpdateStatus()
	})
}

// SetFieldMaps sets the "field_maps" field.
func (u *RequestRewriteRuleUpsertBulk) SetFieldMaps(v []objects.RequestRewriteFieldMap) *RequestRewriteRuleUpsertBulk {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.SetFieldMaps(v)
	})
}

// UpdateFieldMaps sets the "field_maps" field to the value that was provided on create.
func (u *RequestRewriteRuleUpsertBulk) UpdateFieldMaps() *RequestRewriteRuleUpsertBulk {
	return u.Update(func(s *RequestRewriteRuleUpsert) {
		s.UpdateFieldMaps()
	})
}

// Exec executes the query.
func (u *RequestRewriteRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RequestRewriteRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestRewriteRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestRewriteRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
