// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/requestrewriterule"
	"github.com/looplj/axonhub/internal/objects"
)

// RequestRewriteRuleUpdate is the builder for updating RequestRewriteRule entities.
type RequestRewriteRuleUpdate struct {
	config
	hooks     []Hook
	mutation  *RequestRewriteRuleMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RequestRewriteRuleUpdate builder.
func (_u *RequestRewriteRuleUpdate) Where(ps ...predicate.RequestRewriteRule) *RequestRewriteRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RequestRewriteRuleUpdate) SetUpdatedAt(v time.Time) *RequestRewriteRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *RequestRewriteRuleUpdate) SetDeletedAt(v int) *RequestRewriteRuleUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *RequestRewriteRuleUpdate) SetNillableDeletedAt(v *int) *RequestRewriteRuleUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *RequestRewriteRuleUpdate) AddDeletedAt(v int) *RequestRewriteRuleUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *RequestRewriteRuleUpdate) SetName(v string) *RequestRewriteRuleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RequestRewriteRuleUpdate) SetNillableName(v *string) *RequestRewriteRuleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RequestRewriteRuleUpdate) SetDescription(v string) *RequestRewriteRuleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RequestRewriteRuleUpdate) SetNillableDescription(v *string) *RequestRewriteRuleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetModelPattern sets the "model_pattern" field.
func (_u *RequestRewriteRuleUpdate) SetModelPattern(v string) *RequestRewriteRuleUpdate {
	_u.mutation.SetModelPattern(v)
	return _u
}

// SetNillableModelPattern sets the "model_pattern" field if the given value is not nil.
func (_u *RequestRewriteRuleUpdate) SetNillableModelPattern(v *string) *RequestRewriteRuleUpdate {
	if v != nil {
		_u.SetModelPattern(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RequestRewriteRuleUpdate) SetStatus(v requestrewriterule.Status) *RequestRewriteRuleUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RequestRewriteRuleUpdate) SetNillableStatus(v *requestrewriterule.Status) *RequestRewriteRuleUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFieldMaps sets the "field_maps" field.
func (_u *RequestRewriteRuleUpdate) SetFieldMaps(v []objects.RequestRewriteFieldMap) *RequestRewriteRuleUpdate {
	_u.mutation.SetFieldMaps(v)
	return _u
}

// AppendFieldMaps appends value to the "field_maps" field.
func (_u *RequestRewriteRuleUpdate) AppendFieldMaps(v []objects.RequestRewriteFieldMap) *RequestRewriteRuleUpdate {
	_u.mutation.AppendFieldMaps(v)
	return _u
}

// Mutation returns the RequestRewriteRuleMutation object of the builder.
func (_u *RequestRewriteRuleUpdate) Mutation() *RequestRewriteRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequestRewriteRuleUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestRewriteRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequestRewriteRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestRewriteRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RequestRewriteRuleUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if requestrewriterule.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized requestrewriterule.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := requestrewriterule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestRewriteRuleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := requestrewriterule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RequestRewriteRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelPattern(); ok {
		if err := requestrewriterule.ModelPatternValidator(v); err != nil {
			return &ValidationError{Name: "model_pattern", err: fmt.Errorf(`ent: validator failed for field "RequestRewriteRule.model_pattern": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := requestrewriterule.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RequestRewriteRule.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RequestRewriteRuleUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RequestRewriteRuleUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RequestRewriteRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestrewriterule.Table, requestrewriterule.Columns, sqlgraph.NewFieldSpec(requestrewriterule.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(requestrewriterule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(requestrewriterule.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(requestrewriterule.FieldDeletedAt, field.TypeInt, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(requestrewriterule.FieldUserID, field.TypeInt)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(requestrewriterule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(requestrewriterule.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelPattern(); ok {
		_spec.SetField(requestrewriterule.FieldModelPattern, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(requestrewriterule.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.FieldMaps(); ok {
		_spec.SetField(requestrewriterule.FieldFieldMaps, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFieldMaps(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, requestrewriterule.FieldFieldMaps, value)
		})
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestrewriterule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequestRewriteRuleUpdateOne is the builder for updating a single RequestRewriteRule entity.
type RequestRewriteRuleUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RequestRewriteRuleMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RequestRewriteRuleUpdateOne) SetUpdatedAt(v time.Time) *RequestRewriteRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *RequestRewriteRuleUpdateOne) SetDeletedAt(v int) *RequestRewriteRuleUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *RequestRewriteRuleUpdateOne) SetNillableDeletedAt(v *int) *RequestRewriteRuleUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *RequestRewriteRuleUpdateOne) AddDeletedAt(v int) *RequestRewriteRuleUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *RequestRewriteRuleUpdateOne) SetName(v string) *RequestRewriteRuleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RequestRewriteRuleUpdateOne) SetNillableName(v *string) *RequestRewriteRuleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RequestRewriteRuleUpdateOne) SetDescription(v string) *RequestRewriteRuleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RequestRewriteRuleUpdateOne) SetNillableDescription(v *string) *RequestRewriteRuleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetModelPattern sets the "model_pattern" field.
func (_u *RequestRewriteRuleUpdateOne) SetModelPattern(v string) *RequestRewriteRuleUpdateOne {
	_u.mutation.SetModelPattern(v)
	return _u
}

// SetNillableModelPattern sets the "model_pattern" field if the given value is not nil.
func (_u *RequestRewriteRuleUpdateOne) SetNillableModelPattern(v *string) *RequestRewriteRuleUpdateOne {
	if v != nil {
		_u.SetModelPattern(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RequestRewriteRuleUpdateOne) SetStatus(v requestrewriterule.Status) *RequestRewriteRuleUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RequestRewriteRuleUpdateOne) SetNillableStatus(v *requestrewriterule.Status) *RequestRewriteRuleUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFieldMaps sets the "field_maps" field.
func (_u *RequestRewriteRuleUpdateOne) SetFieldMaps(v []objects.RequestRewriteFieldMap) *RequestRewriteRuleUpdateOne {
	_u.mutation.SetFieldMaps(v)
	return _u
}

// AppendFieldMaps appends value to the "field_maps" field.
func (_u *RequestRewriteRuleUpdateOne) AppendFieldMaps(v []objects.RequestRewriteFieldMap) *RequestRewriteRuleUpdateOne {
	_u.mutation.AppendFieldMaps(v)
	return _u
}

// Mutation returns the RequestRewriteRuleMutation object of the builder.
func (_u *RequestRewriteRuleUpdateOne) Mutation() *RequestRewriteRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the RequestRewriteRuleUpdate builder.
func (_u *RequestRewriteRuleUpdateOne) Where(ps ...predicate.RequestRewriteRule) *RequestRewriteRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequestRewriteRuleUpdateOne) Select(field string, fields ...string) *RequestRewriteRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RequestRewriteRule entity.
func (_u *RequestRewriteRuleUpdateOne) Save(ctx context.Context) (*RequestRewriteRule, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestRewriteRuleUpdateOne) SaveX(ctx context.Context) *RequestRewriteRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequestRewriteRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestRewriteRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RequestRewriteRuleUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if requestrewriterule.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized requestrewriterule.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := requestrewriterule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestRewriteRuleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := requestrewriterule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RequestRewriteRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelPattern(); ok {
		if err := requestrewriterule.ModelPatternValidator(v); err != nil {
			return &ValidationError{Name: "model_pattern", err: fmt.Errorf(`ent: validator failed for field "RequestRewriteRule.model_pattern": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := requestrewriterule.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RequestRewriteRule.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RequestRewriteRuleUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RequestRewriteRuleUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RequestRewriteRuleUpdateOne) sqlSave(ctx context.Context) (_node *RequestRewriteRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestrewriterule.Table, requestrewriterule.Columns, sqlgraph.NewFieldSpec(requestrewriterule.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RequestRewriteRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requestrewriterule.FieldID)
		for _, f := range fields {
			if !requestrewriterule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requestrewriterule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(requestrewriterule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(requestrewriterule.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(requestrewriterule.FieldDeletedAt, field.TypeInt, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(requestrewriterule.FieldUserID, field.TypeInt)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(requestrewriterule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(requestrewriterule.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelPattern(); ok {
		_spec.SetField(requestrewriterule.FieldModelPattern, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(requestrewriterule.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.FieldMaps(); ok {
		_spec.SetField(requestrewriterule.FieldFieldMaps, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFieldMaps(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, requestrewriterule.FieldFieldMaps, value)
		})
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &RequestRewriteRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestrewriterule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
