// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/requestrewriterule"
)

// RequestRewriteRuleDelete is the builder for deleting a RequestRewriteRule entity.
type RequestRewriteRuleDelete struct {
	config
	hooks    []Hook
	mutation *RequestRewriteRuleMutation
}

// Where appends a list predicates to the RequestRewriteRuleDelete builder.
func (_d *RequestRewriteRuleDelete) Where(ps ...predicate.RequestRewriteRule) *RequestRewriteRuleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RequestRewriteRuleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RequestRewriteRuleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RequestRewriteRuleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(requestrewriterule.Table, sqlgraph.NewFieldSpec(requestrewriterule.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RequestRewriteRuleDeleteOne is the builder for deleting a single RequestRewriteRule entity.
type RequestRewriteRuleDeleteOne struct {
	_d *RequestRewriteRuleDelete
}

// Where appends a list predicates to the RequestRewriteRuleDelete builder.
func (_d *RequestRewriteRuleDeleteOne) Where(ps ...predicate.RequestRewriteRule) *RequestRewriteRuleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RequestRewriteRuleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{requestrewriterule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RequestRewriteRuleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
