// Code generated by ent, DO NOT EDIT.

package requestrewriterule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldEQ(FieldUserID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldEQ(FieldDescription, v))
}

// ModelPattern applies equality check predicate on the "model_pattern" field. It's identical to ModelPatternEQ.
func ModelPattern(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldEQ(FieldModelPattern, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldLTE(FieldDeletedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldNotNull(FieldUserID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldContainsFold(FieldDescription, v))
}

// ModelPatternEQ applies the EQ predicate on the "model_pattern" field.
func ModelPatternEQ(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldEQ(FieldModelPattern, v))
}

// ModelPatternNEQ applies the NEQ predicate on the "model_pattern" field.
func ModelPatternNEQ(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldNEQ(FieldModelPattern, v))
}

// ModelPatternIn applies the In predicate on the "model_pattern" field.
func ModelPatternIn(vs ...string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldIn(FieldModelPattern, vs...))
}

// ModelPatternNotIn applies the NotIn predicate on the "model_pattern" field.
func ModelPatternNotIn(vs ...string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldNotIn(FieldModelPattern, vs...))
}

// ModelPatternGT applies the GT predicate on the "model_pattern" field.
func ModelPatternGT(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldGT(FieldModelPattern, v))
}

// ModelPatternGTE applies the GTE predicate on the "model_pattern" field.
func ModelPatternGTE(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldGTE(FieldModelPattern, v))
}

// ModelPatternLT applies the LT predicate on the "model_pattern" field.
func ModelPatternLT(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldLT(FieldModelPattern, v))
}

// ModelPatternLTE applies the LTE predicate on the "model_pattern" field.
func ModelPatternLTE(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldLTE(FieldModelPattern, v))
}

// ModelPatternContains applies the Contains predicate on the "model_pattern" field.
func ModelPatternContains(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldContains(FieldModelPattern, v))
}

// ModelPatternHasPrefix applies the HasPrefix predicate on the "model_pattern" field.
func ModelPatternHasPrefix(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldHasPrefix(FieldModelPattern, v))
}

// ModelPatternHasSuffix applies the HasSuffix predicate on the "model_pattern" field.
func ModelPatternHasSuffix(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldHasSuffix(FieldModelPattern, v))
}

// ModelPatternEqualFold applies the EqualFold predicate on the "model_pattern" field.
func ModelPatternEqualFold(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldEqualFold(FieldModelPattern, v))
}

// ModelPatternContainsFold applies the ContainsFold predicate on the "model_pattern" field.
func ModelPatternContainsFold(v string) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldContainsFold(FieldModelPattern, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.FieldNotIn(FieldStatus, vs...))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RequestRewriteRule) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RequestRewriteRule) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RequestRewriteRule) predicate.RequestRewriteRule {
	return predicate.RequestRewriteRule(sql.NotPredicates(p))
}
