package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/ent/requestrewriterule"
	"github.com/looplj/axonhub/internal/objects"
)

// CreateRequestRewriteRule is the resolver for the createRequestRewriteRule field.
func (r *mutationResolver) CreateRequestRewriteRule(ctx context.Context, input ent.CreateRequestRewriteRuleInput) (*ent.RequestRewriteRule, error) {
	return r.requestRewriteRuleService.CreateRule(ctx, input)
}

// UpdateRequestRewriteRule is the resolver for the updateRequestRewriteRule field.
func (r *mutationResolver) UpdateRequestRewriteRule(ctx context.Context, id objects.GUID, input ent.UpdateRequestRewriteRuleInput) (*ent.RequestRewriteRule, error) {
	return r.requestRewriteRuleService.UpdateRule(ctx, id.ID, &input)
}

// DeleteRequestRewriteRule is the resolver for the deleteRequestRewriteRule field.
func (r *mutationResolver) DeleteRequestRewriteRule(ctx context.Context, id objects.GUID) (bool, error) {
	if err := r.requestRewriteRuleService.DeleteRule(ctx, id.ID); err != nil {
		return false, err
	}

	return true, nil
}

// UpdateRequestRewriteRuleStatus is the resolver for the updateRequestRewriteRuleStatus field.
func (r *mutationResolver) UpdateRequestRewriteRuleStatus(ctx context.Context, id objects.GUID, status requestrewriterule.Status) (bool, error) {
	if _, err := r.requestRewriteRuleService.UpdateRuleStatus(ctx, id.ID, status); err != nil {
		return false, err
	}

	return true, nil
}

// BulkDeleteRequestRewriteRules is the resolver for the bulkDeleteRequestRewriteRules field.
func (r *mutationResolver) BulkDeleteRequestRewriteRules(ctx context.Context, ids []*objects.GUID) (bool, error) {
	if err := r.requestRewriteRuleService.BulkDeleteRules(ctx, objects.IntGuids(ids)); err != nil {
		return false, err
	}

	return true, nil
}

// BulkEnableRequestRewriteRules is the resolver for the bulkEnableRequestRewriteRules field.
func (r *mutationResolver) BulkEnableRequestRewriteRules(ctx context.Context, ids []*objects.GUID) (bool, error) {
	if err := r.requestRewriteRuleService.BulkEnableRules(ctx, objects.IntGuids(ids)); err != nil {
		return false, err
	}

	return true, nil
}

// BulkDisableRequestRewriteRules is the resolver for the bulkDisableRequestRewriteRules field.
func (r *mutationResolver) BulkDisableRequestRewriteRules(ctx context.Context, ids []*objects.GUID) (bool, error) {
	if err := r.requestRewriteRuleService.BulkDisableRules(ctx, objects.IntGuids(ids)); err != nil {
		return false, err
	}

	return true, nil
}
